project:
  type: book
  output-dir: docs

# Quarto options for books
# https://quarto.org/docs/reference/projects/books.html
book:
  title: "Computational Publishing Service Demo"
  author: "Simon Worthington"
  date: "2024-03-22"
  # this section determines which files will be added to the book as chapters
  chapters:
    - index.qmd
    - copyright-page.ipynb
    - essay.ipynb
    - painting-collection.ipynb
    - data-analysis.ipynb
  repo-url: https://github.com/NFDI4Culture/CPS-Demo
  repo-actions: [edit]
  downloads: [pdf,docx,epub]
  cover-image: cover-sml.jpg

# Quarto allows commenting using either Hypothesis or Utterances
# https://quarto.org/docs/reference/projects/books.html#comments
comments:
  hypothesis: true

format:
  # options for HTML output
  # https://quarto.org/docs/reference/formats/html.html
  html:
    number-sections: false
    # Quarto allows a number of pre-packaged themes for the HTML version
    # You can choose between them using the documentation at https://quarto.org/docs/output-formats/html-themes.html
    theme: darkly
  # options for PDF output 
  # https://quarto.org/docs/reference/formats/pdf.html
  pdf:
    documentclass: book
  docx: 
    toc: true
  epub: 
    toc: true    
